[package]
name = "jed"
version = "0.3.0"
edition = "2024"

[lints.clippy]
pedantic = "warn"

[profile.dev]
opt-level = 0 
# opt-level = 1

[profile.profiling]
inherits = "release"
debug = true

[dependencies]
lexopt = "0.3.1"
jed-macros = { path = "../jed-macros" }

[dev-dependencies]
criterion = "0.5.1"
