extern crate jed_macros;
mod error;
mod frame;
pub mod memory;
mod modules;
mod object;
pub mod operation;
pub mod program;
mod span;
mod utils;
pub mod vm;
const MAGIC_NUMBER: &[u8] = "jed".as_bytes();
